name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Rust checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v2
      - name: Run format
        run: cargo make format
      - name: Run check
        run: cargo make check
      - name: Run clippy
        run: cargo make clippy
      - name: Run test
        run: cargo make test
      - name: Generate code coverage
        run: cargo make coverage
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
