name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Rust checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: config_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      influxdb:
        image: influxdb:latest
        env:
          INFLUXDB_DB: rooms
          INFLUXDB_ADMIN_USER: influxdb_admin
          INFLUXDB_ADMIN_PASSWORD: influxdb_password
          INFLUXDB_HTTP_AUTH_ENABLED: true
          INFLUXDB_DATA_QUERY_LOG_ENABLED: false
        ports:
          - 8086:8086
        # Set health checks to wait until influxdb has started
        options: >-
          --health-cmd "curl -sI 127.0.0.1:8086/ping | grep -q \"204 No Content\""
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v2
      - name: Run format
        run: cargo make format
      - name: Run check
        run: cargo make check
      - name: Run clippy
        run: cargo make clippy
      - name: Run test
        run: cargo make test
        env:
          INFLUXDB_HOST: http://localhost:8086
      - name: Generate code coverage
        run: cargo make coverage
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
