name: Security
on:
  push:
    branches:
      - master
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    branches:
      - master
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 0 * * *"
jobs:
  security_audit:
    name: Audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-audit binary crate
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
      - uses: davidB/rust-cargo-make@v1
      - name: Run audit
        run: cargo make audit
